### ISSUE TITLE
Clicking Feature > Basalt Columns > Height Base/Spread crashes the app and causes loss of unsaved data

### ISSUE THREAD

**Issue by TBlazeWarriorT** [syldium/worldgen#10]
Feature > Basalt Columns > Height Base/Spread crashes the app and makes it a full grayscreen until you refresh the page every time for me on Firefox.
Refreshing the page wipes out anything that was on my datapack, doesn't seem to get cached, making me have to reimport the datapack or lose everything if I don't have a backup.
Reimporting the datapack is also annoying because it can cause a few visual or actual bugs on the imported data.

**Comment by TBlazeWarriorT** [comment]
![image](https://user-images.githubusercontent.com/25572454/126886950-b3333146-2f21-4cc0-a3c2-8a6d2ab0057a.png)
^visual bug example
and when I refresh the page, the namespace is kept and cached properly, but all contents of the datapack are wiped out.

**Comment by syldium** [comment]
Should be fixed in the 1.17 version
