### ISSUE TITLE
minecraft:spruce_snowy feature is referenced but does not exist

### ISSUE THREAD

**Issue by TBlazeWarriorT** [syldium/worldgen#11]
The app tries to add and reference a feature called spruce_snowy, but it does not exist in the original game files and breaks the datapack.
The correct name is probably minecraft:trees_snowy not spruce.

**Comment by syldium** [comment]
The configured feature `minecraft:spruce_snowy` exists in 1.16.5, which is the version of Minecraft currently targeted at the moment. `minecraft:trees_snowy` exists only in 1.17 and is available in the [currently highly-unstable-and-unusable future version](https://worldgen.pages.dev/) of the generator.

**Comment by TBlazeWarriorT** [comment]
Oh sorry, my friend jebaited me, then I checked the game files looking for it and accidentally looked at the 1.17 game files, giving me a double false confirmation of the bug. Thx for telling
