### ISSUE TITLE
use existing datpack

### ISSUE THREAD

**Issue by snitasss** [syldium/worldgen#13]
[Elysium_1_17.zip](https://github.com/syldium/worldgen/files/7076462/Elysium_1_17.zip)
 

I am trying to upload this but it doesn't seem to load.

**Comment by syldium** [comment]
Hi,
This datapack loads correctly for me. Do you get an error like `File is not a .zip` ?

**Comment by snitasss** [comment]
No, I used the previous version to create the datapack, so it's actually for 1.16

**Comment by snitasss** [comment]
it says "datapack imported" but then what

**Comment by ilovehorrorcats** [comment]
ive also noticed this too

**Comment by syldium** [comment]
What operating system and browser are you using? With which datapack?

**Comment by ilovehorrorcats** [comment]
this is fixed now but I was using kubuntu 21.04 on firefox 94.0
