### ISSUE TITLE
some kinda datafixer for dimension datapacks?

### ISSUE THREAD

**Issue by stovan12** [syldium/worldgen#17]
Thanks for fixing the other problems I had so fast, appreciate a bunch.
I like making custom dimensions but every time the game updates they get completely fucked and I have to start over, do you know of any projects that datafix datapacks? would it be something that interests you? (would be alot of work tho)

**Comment by syldium** [comment]
Hi, you may be interested in [Misode's data pack upgrade tool](https://misode.github.io/upgrader).

**Comment by stovan12** [comment]
wow, it worked perfectly!!!! I am ecstatic rn, I thought these datapacks would forever be broken, thank you very much.
