### ISSUE TITLE
Potential issue attempting to use existing datapack

### ISSUE THREAD

**Issue by careful-analysis** [syldium/worldgen#22]
Receiving the message "Uncaught Error: Invalid datapack: no pack.mcmeta" which seems like a catch all, given the zip contains pack.mcmeta. The pack itself was built here, downloaded (and edited slightly by hand to remove the unremovable spawn cost entries in the biome editor). Is there an inherent checksum I'm missing by editing a json file, rezipping, and trying to reupload? Or something simple going on with compression? I'm using basic zip 3.0 in BSD.
[generated_datapack.zip](https://github.com/syldium/worldgen/files/7621930/generated_datapack.zip)

Thanks in advance for any help troubleshooting this. I hope it's not a "duh" moment in the end.

**Comment by syldium** [comment]
Hi,
The `pack.mcmeta` file and the `data/` folder must be at the root of the .zip, without any intermediate folder. Usually you should compress the files in the folder rather than the folder containing them.

**Comment by careful-analysis** [comment]
Ah. A "duh" moment, as I feared. Got lazy with -r in hand. Thank you, and lovely work you've done on this tool!
