### ISSUE TITLE
Ive noticed for 1.18 some biome names changed

### ISSUE THREAD

**Issue by ilovehorrorcats** [syldium/worldgen#25]
so for example snowy_tundra should be changed into snowy_plains and stuff like that. It is causing errors for 1.18

**Comment by ilovehorrorcats** [comment]
wait why is this closed

**Comment by syldium** [comment]
The biomes list has been updated for Minecraft 1.18 in the [published version](https://worldgen.syldium.dev).

**Comment by ilovehorrorcats** [comment]
Ive just noticed this thx for fixin it
