### ISSUE TITLE
Invalid features

### ISSUE THREAD

**Issue by ghost** [syldium/worldgen#27]
It seems like 1.18 version still has removed 1.17 objects, when loading a 1.18 made with syldium console says:

>.... [18:40:25 ERROR]: Feature: Not a JSON object: "minecraft:ore_granite"; Not a JSON object: "minecraft:ore_tuff"; Not a JSON object: "minecraft:ore_gravel"; Not a JSON object: "minecraft:ore_dirt"; Not a JSON object: "minecraft:ore_diorite"; Not a JSON object: "minecraft:ore_coal"; Not a JSON object: "minecraft:ore_andesite"; Not a JSON object: "minecraft:disk_gravel"; Not a JSON object: "minecraft:disk_clay"
>.... [18:40:25 ERROR]: Feature: Not a JSON object: "minecraft:pointed_dripstone"; Not a JSON object: "minecraft:large_dripstone"; Not a JSON object: "minecraft:dripstone_cluster"; Not a JSON object: "minecraft:dripleaf"; Not a JSON object: "minecraft:cave_vine"
>.... [18:40:25 ERROR]: Feature: Not a JSON object: "minecraft:spring_water"; Not a JSON object: "minecraft:patch_tall_grass"; Not a JSON object: "minecraft:patch_red_mushroom"; Not a JSON object: "minecraft:patch_brown_mushroom"; Not a JSON object: "minecraft:glow_lichen"; Not a JSON object: "custom:test_forest_bushes"; Not a JSON object: "custom:patch_grass_underground"; Not a JSON object: "custom:jack_o_lantern_patch"; Not a JSON object: "custom:cobweb_patch"
>.... [18:40:25 ERROR]: Feature: Not a JSON object: "minecraft:ore_granite"; Not a JSON object: "minecraft:ore_tuff"; Not a JSON object: "minecraft:ore_gravel"; Not a JSON object: "minecraft:ore_dirt"; Not a JSON object: "minecraft:ore_diorite"; Not a JSON object: "minecraft:ore_coal"; Not a JSON object: "minecraft:ore_andesite"; Not a JSON object: "minecraft:disk_gravel"; Not a JSON object: "minecraft:disk_clay"
>.... [18:40:25 ERROR]: Feature: Not a JSON object: "minecraft:pointed_dripstone"; Not a JSON object: "minecraft:large_dripstone"; Not a JSON object: "minecraft:dripstone_cluster"; Not a JSON object: "minecraft:dripleaf"; Not a JSON object: "minecraft:cave_vine"
>.... [18:40:25 ERROR]: Feature: Not a JSON object: "minecraft:spring_water"; Not a JSON object: "minecraft:patch_tall_grass"; Not a JSON object: "minecraft:patch_red_mushroom"; Not a JSON object: "minecraft:patch_brown_mushroom"; Not a JSON object: "minecraft:glow_lichen"; Not a JSON object: "custom:test_forest_bushes"; Not a JSON object: "custom:patch_grass_underground"; Not a JSON object: "custom:jack_o_lantern_patch"; Not a JSON object: "custom:cobweb_patch"

**Comment by RemRemEgg** [comment]
I messed around a little and found that its looking for something along the lines of 
`[
    {"feature":"minecraft:blue_ice","placement":[]},
    {"feature":"minecraft:ice_patch","placement":[]}
]`
However, i dont know what its looking for in `"placement":[]`. Also, with configured_features, the `"type"` field no longer accepts `"minecraft:decorated"`. I cant find anything online about what the new generation is looking for, but i hope my findings help!

**Comment by syldium** [comment]
Thanks for your findings.

Placement modifiers (previously called *decorators*) are no longer placed in `configured_feature`s with the `decorated` type but in `placed_feature`s with a list of modifiers in `placement`. There was a problem where the `placement` field was removed in the editor, which produced the same kind of in-game error as in the original message. If the issue still exists after the linked commit, could you indicate for which feature for example?
