### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by cakeartist** [syldium/worldgen#43]
PLEASE, help me... I play in 1.16 for the most part because it has some diverse mods, and i love your generator. however, it appears that I can no longer make data packs for 1.16. if you have a new link or a file or something that can help me use your program for 1.16 that would be incredible. thank you for your support!

**Comment by syldium** [comment]
You can use the [old version hosted here](https://master.worldgen.pages.dev), but it does not actively receive updates.

**Comment by cakeartist** [comment]
thank you so much!!! i tried looking for a link to the old version but i dont use github very much at all, big help thank ya!
