### ISSUE TITLE
Missing keys in dimension type 1.19

### ISSUE THREAD

**Issue by ghost** [syldium/worldgen#44]
"max_inclusive": 7
"min_inclusive": 0,
"monster_spawn_block_light_limit": 0
"monster_spawn_light_level": {
"type": "minecraft:uniform",

these keys are missing from syldium dimension type for 1.19.2, trying to load gives this error in console:

[17:49:06] [ServerMain/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: No key monster_spawn_block_light_limit in MapLike[{"logical_height":384,"infiniburn":"#minecraft:infiniburn_overworld","effects":"minecraft:overworld","ambient_light":0,"respawn_anchor_works":false,"has_raids":true,"min_y":-64,"height":384,"natural":true,"coordinate_scale":1,"piglin_safe":false,"bed_works":true,"has_skylight":true,"has_ceiling":false,"ultrawarm":false}]; No key monster_spawn_light_level in MapLike[{"logical_height":384,"infiniburn":"#minecraft:infiniburn_overworld","effects":"minecraft:overworld","ambient_light":0,"respawn_anchor_works":false,"has_raids":true,"min_y":-64,"height":384,"natural":true,"coordinate_scale":1,"piglin_safe":false,"bed_works":true,"has_skylight":true,"has_ceiling":false,"ultrawarm":false}]

**Comment by syldium** [comment]
Thanks for the heads up! :+1:
