### ISSUE TITLE
how do you go in the dimensions without commands?

### ISSUE THREAD

**Issue by therandomdudejajaja** [syldium/worldgen#60]
i believe you can use some sort of command for it but i wanna make portals for it, is that a thing?

**Comment by syldium** [comment]
The game does not currently have a built-in way to create custom portals. Some mods expose a way to create data-driven portals, and in most datapacks you will find, they have their own code for this. There are some tutorials available if you're interested.

**Comment by therandomdudejajaja** [comment]
alright thanks
